export enum DeadlineType {
  CONTESTACAO = 'CONTESTACAO',
  REPLICA = 'REPLICA',
  RECURSO = 'RECURSO',
  MANIFESTACAO = 'MANIFESTACAO',
  PAGAMENTO = 'PAGAMENTO',
  AUDIENCIA = 'AUDIENCIA',
  OUTRO = 'OUTRO',
}
