export enum NotificationType {
  DEADLINE_CREATED = 'DEADLINE_CREATED',
  DEADLINE_UPDATED = 'DEADLINE_UPDATED',
  DEADLINE_DUE = 'DEADLINE_DUE',
  CASE_CREATED = 'DEADLINE_CREATED',
  CASE_DELETED = 'DEADLINE_CREATED',
  CASE_UPDATED = 'DEADLINE_CREATED',
}
