export type ModalType =
  | 'client-cases'
  | 'register-client'
  | 'case'
  | 'register-case'
  | 'update-case'
  | 'update-client'
  | 'delete-client'
  | 'upload-case-files'
  | 'confirm'
  | 'success'
  | 'error'
  | 'deadlines'
  | 'create-deadline'
  | 'case-files'
  | null;
