import { fakeUserDatabase } from './users';
import { CasesStatus } from '../../types/CasesStatus';

export const fakeCases = [
  {
    client: fakeUserDatabase[3]!._id,
    lawyers: [fakeUserDatabase[0]!._id, fakeUserDatabase[1]!._id],
    processNumber: '01119418441616-44156',
    title: 'Ação de indenização por danos morais',
    description:
      'O cliente busca reparação por danos morais decorrentes de uma cobrança indevida realizada pela empresa X. O processo está em fase de instrução, aguardando audiência para oitiva de testemunhas.',
    court: 'STJ',
    courtDivision: '5ª Vara Cívil',
    status: CasesStatus.open,
  },
  {
    client: fakeUserDatabase[3]!._id,
    lawyers: [fakeUserDatabase[0]!._id, fakeUserDatabase[1]!._id],
    processNumber: '55329184722017-11422',
    title: 'Ação de usucapião urbano',
    description:
      'O cliente busca o reconhecimento de posse prolongada de um imóvel urbano utilizado há mais de 15 anos ininterruptos.',
    court: 'TJ-RJ',
    courtDivision: '7ª Vara de Registros Públicos',
    status: CasesStatus.open,
  },
  {
    client: fakeUserDatabase[3]!._id,
    lawyers: [fakeUserDatabase[0]!._id],
    processNumber: '77193840255120-66821',
    title: 'Ação de cobrança por inadimplência contratual',
    description:
      'A parte autora busca receber valores devidos referentes a um contrato de prestação de serviços não pago.',
    court: 'TJ-SP',
    courtDivision: '2ª Vara Cível',
    status: CasesStatus.closed,
  },
  {
    client: fakeUserDatabase[3]!._id,
    lawyers: [fakeUserDatabase[1]!._id],
    processNumber: '91283746501923-44177',
    title: 'Ação de danos materiais por acidente de trânsito',
    description:
      'O cliente busca ressarcimento pelos danos causados ao seu veículo após colisão envolvendo terceiro.',
    court: 'TJ-SP',
    courtDivision: '14ª Vara Cível',
    status: CasesStatus.open,
  },
  {
    client: fakeUserDatabase[3]!._id,
    lawyers: [fakeUserDatabase[0]!._id, fakeUserDatabase[1]!._id],
    processNumber: '91283747777923-44177',
    title: 'Ação de danos morais',
    description: 'O cliente busca ressarcimento pelos danos morais.',
    court: 'TJ-SP',
    courtDivision: '14ª Vara Cível',
    status: CasesStatus.closed,
  },
  {
    client: fakeUserDatabase[2]!._id,
    lawyers: [fakeUserDatabase[0]!._id],
    processNumber: '91244458777923-44177',
    title: 'Ação de danos à imagem',
    description: 'O cliente busca ressarcimento pelos danos causados à sua imagem publica.',
    court: 'TJ-SP',
    courtDivision: '14ª Vara Cível',
    status: CasesStatus.open,
  },
  {
    client: fakeUserDatabase[2]!._id,
    lawyers: [fakeUserDatabase[0]!._id],
    processNumber: '91283585877923-44177',
    title: 'Ação de pensão por morte',
    description: 'O cliente busca pensão pela morte do marido',
    court: 'TJ-SP',
    courtDivision: '14ª Vara Cível',
    status: CasesStatus.closed,
  },
  {
    client: fakeUserDatabase[4]!._id,
    lawyers: [fakeUserDatabase[2]!._id],
    processNumber: '12345678901234-56789',
    title: 'Ação de revisão contratual',
    description:
      'O cliente solicita revisão das cláusulas de um contrato de financiamento devido a juros abusivos.',
    court: 'TJ-MG',
    courtDivision: '3ª Vara Cível',
    status: CasesStatus.open,
  },
  {
    client: fakeUserDatabase[5]!._id,
    lawyers: [fakeUserDatabase[1]!._id, fakeUserDatabase[2]!._id],
    processNumber: '98765432109876-54321',
    title: 'Ação de despejo por falta de pagamento',
    description:
      'O cliente busca a retomada de imóvel alugado devido à inadimplência do locatário.',
    court: 'TJ-SP',
    courtDivision: '10ª Vara Cível',
    status: CasesStatus.closed,
  },
  {
    client: fakeUserDatabase[6]!._id,
    lawyers: [fakeUserDatabase[1]!._id],
    processNumber: '11223344556677-88990',
    title: 'Ação de guarda compartilhada',
    description: 'O cliente busca a guarda compartilhada do filho menor após separação.',
    court: 'TJ-RJ',
    courtDivision: '1ª Vara de Família',
    status: CasesStatus.open,
  },
  {
    client: fakeUserDatabase[7]!._id,
    lawyers: [fakeUserDatabase[0]!._id],
    processNumber: '99887766554433-22110',
    title: 'Ação de inventário',
    description:
      'O cliente solicita abertura de inventário para partilha de bens após falecimento de parente.',
    court: 'TJ-MG',
    courtDivision: '2ª Vara de Órfãos e Sucessões',
    status: CasesStatus.closed,
  },
  {
    client: fakeUserDatabase[8]!._id,
    lawyers: [fakeUserDatabase[2]!._id],
    processNumber: '55667788990011-22334',
    title: 'Ação de alimentos',
    description: 'O cliente busca fixação de pensão alimentícia para o filho menor.',
    court: 'TJ-SP',
    courtDivision: '5ª Vara de Família',
    status: CasesStatus.open,
  },
  {
    client: fakeUserDatabase[9]!._id,
    lawyers: [fakeUserDatabase[0]!._id],
    processNumber: '33445566778899-00112',
    title: 'Ação de rescisão contratual',
    description:
      'O cliente deseja rescindir contrato de compra e venda de imóvel por descumprimento de cláusulas.',
    court: 'TJ-RJ',
    courtDivision: '6ª Vara Cível',
    status: CasesStatus.closed,
  },
  {
    client: fakeUserDatabase[10]!._id,
    lawyers: [fakeUserDatabase[1]!._id, fakeUserDatabase[0]!._id],
    processNumber: '22113344556677-88990',
    title: 'Ação de reconhecimento de união estável',
    description:
      'O cliente busca reconhecimento judicial de união estável para fins de partilha de bens.',
    court: 'TJ-SP',
    courtDivision: '8ª Vara de Família',
    status: CasesStatus.open,
  },
  {
    client: fakeUserDatabase[11]!._id,
    lawyers: [fakeUserDatabase[0]!._id],
    processNumber: '77889900112233-44556',
    title: 'Ação de indenização por erro médico',
    description:
      'O cliente busca indenização por danos decorrentes de erro médico em procedimento cirúrgico.',
    court: 'TJ-MG',
    courtDivision: '4ª Vara Cível',
    status: CasesStatus.closed,
  },
];